name: ASP.NET Framework Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
    
    - name: Restore Packages
      run: nuget restore Offline-CDN.sln
    
    - name: Build solution
      run: msbuild Offline-CDN.sln -t:rebuild -property:Configuration=Release

  deploy:
    runs-on: [self-hosted]
    
    steps:
    - name: Deploy to IIS
      run: Copy-Item ${{env.DOTNET_ROOT}}/Offline-CDN/* C:\Users\Romit\Documents\Deployments\Offline-CDN -Recurse -Force

